### ISSUE TITLE
API 2 not working

### ISSUE THREAD

**Issue by ChiragChauhan4579** [l4rm4nd/LinkedInDumper#12]
I am trying to use the code but cannot pass through API 2. I tried checking into LinkedIn and its available voyager calls but did not find another link.

api2 = "https://www.linkedin.com/voyager/api/search/dash/clusters?decorationId=com.linkedin.voyager.dash.deco.search.SearchClusterCollection-165&origin=COMPANY_PAGE_CANNED_SEARCH&q=all&query=(flagshipSearchIntent:SEARCH_SRP,queryParameters:(currentCompany:List(" + str(companyID) + "),resultType:List(PEOPLE)),includeFiltersInResponse:false)&count=" + str(paging_count)+ "&start=0"

Can you please help if it is still working for you?

**Comment by l4rm4nd** [comment]
Hi @ChiragChauhan4579,

the current LinkedInDumper version still works on my end.

I've tested it right now and no issues so far.

May share your company LinkedIn url you want to enumerate.

**Comment by ChiragChauhan4579** [comment]
Thanks for the quick reply @l4rm4nd. 

This is the company I am looking at: https://www.linkedin.com/company/themlco

**Comment by l4rm4nd** [comment]
Works on my side. No issues at all.

````
[i] Company Name: themlco
[i] Company X-ID: 72135490
[i] LN Employees: 8 employees found
[i] Dumping Date: 16/07/2024 14:53:38
[i] Email Format: {0}.{1}@themlco.com

Progress: [########################################] 1/1

Firstname;Lastname;Email;Position;Gender;Location;Profile
Saurabh;Shahane;saurabh.shahane@themlco.com;Founder CEO at The Machine Learning Company | Kaggle Grandmaster | Enterprise AI and Data Science Solutions | BNI Member |;N/A;Pune;https://www.linkedin.com/in/saurabh-shahane
Chirag;Chauhan;chirag.chauhan@themlco.com;Machine Learning Engineer at The Machine Learning Company | Exploring MLOps and Rust | Kaggle Master;N/A;Upleta;https://www.linkedin.com/in/chirag-chauhan-9a220a195
Govind;Sheshadri;govind.sheshadri@themlco.com;CSE Graduate (2023)| Proficient in C++ JavaScript SQL;N/A;Aurangabad;https://www.linkedin.com/in/govind-sheshadri
Vishwas;Kshirsagar;vishwas.kshirsagar@themlco.com;Helping job-seekers land their dream job - free of charge! | Data Science Mentor @ Topmate.io | Data Science Consultant @ TMLC | Ex - U - Smart AI Lab;N/A;Pune;https://www.linkedin.com/in/k98vishwas

[i] Successfully crawled 4 unique themlco employee(s). Hurray ^_-
````
