### ISSUE TITLE
Private Profiles Requires an Authenticated Session Cookie

### ISSUE THREAD

**Issue by g33k247** [l4rm4nd/LinkedInDumper#3]
**When running the Docker container with the `--include-private-profiles` option, I receive the following error:**

```
[!] Authenticated session cookie required..........] 1/20
    > Set variable permanently in script or use the '--session-cookie' CLI flag!
[debug] ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```

The program exits.

**Removing the `--include-private-profiles` option, I receive the following error:**

```
[!] Authenticated session cookie required..........] 14/20
    > Set variable permanently in script or use the '--session-cookie' CLI flag!
[debug] ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```

**Comment by l4rm4nd** [comment]
> But is it --cookie or is it --session-cookie as the error below implies:
> 
> ```
> > Set variable permanently in script or use the '--session-cookie' CLI flag!
> [debug] ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
> ```

Please read the readme or inspect the python script's help via -h

**Comment by g33k247** [comment]
Yes, the code needs to be updated to reduce confusion on the actual parameter to be passed on the CLI.

**Comment by g33k247** [comment]
However, when I hardcode the session cookie into the script, I get a different result:

``
[!] Authenticated session cookie required.
    > Set variable permanently in script or use the '--session-cookie' CLI flag!
[debug] Exceeded 30 redirects.
```

**Comment by l4rm4nd** [comment]
> Yes, the code needs to be updated to reduce confusion on the actual parameter to be passed on the CLI.

I've fixed the print message when an error occurs. However, the GitHub's readme and the python's scripts help section is pretty straight forward.

You just have to pass your session cookie. Either via CLI or define it permanently in the python script. For the dockerized container I recommend the cli param, as you do not have access to the python script iself.

**Comment by l4rm4nd** [comment]
> However, when I hardcode the session cookie into the script, I get a different result:
> 
> ``
> [!] Authenticated session cookie required.
>     > Set variable permanently in script or use the '--session-cookie' CLI flag!
> [debug] Exceeded 30 redirects.
> ```

Guess you got rate limited due to too many failed tries. LinkedIn is redirecting all your requests, likely to the login page.

Check your cookie whether it is still authenticated. Relogin and grep a new cookie value or wait a bit for cooldown.
