### ISSUE TITLE
No first or last names are reported

### ISSUE THREAD

**Issue by nano6yt3** [l4rm4nd/LinkedInDumper#4]
The tool does not seem to be parsing the names and last names correctly.  All lines look like this "LinkedIn;Member;..."

**Comment by l4rm4nd** [comment]
Please read the readme.

> Furthermore, not all employee profiles are public. The results vary depending on your used LinkedIn account and whether you are befriended with some employees of the company to crawl or not. Therefore, it is sometimes not possible to retrieve the firstname, lastname and profile url of some employee accounts. The script will not display such profiles, as they contain default values such as "LinkedIn" as firstname and "Member" in the lastname. If you want to include such private profiles, please use the CLI flag --include-private-profiles

**Comment by nano6yt3** [comment]
Thank you, yes I was using the --include-private-profiles flag
