### ISSUE TITLE
API change?

### ISSUE THREAD

**Issue by grandmerchant** [l4rm4nd/LinkedInDumper#6]
Curious if it is known if the LinkedIn API has changed - I'm getting errors when running the script telling me to set the cookie. Which I've tried doing both within the script and at the command line.

**Comment by l4rm4nd** [comment]
Hi  @grandmerchant,

you are correct, the script was not working anymore.

I've had some troubleshooting and noticed that LinkedIn is actively blocking the defined user agent string `Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)`.

I've chosen a different user agent for now and it seems to work again. 

See https://github.com/l4rm4nd/LinkedInDumper/commit/c9f2c8825785fc1c653a2ad6169d8dd3ea2a302f.

Thanks for bringing it up!
