### ISSUE TITLE
Can we sponsor you?

### ISSUE THREAD

**Issue by josephlimtech** [l4rm4nd/LinkedInDumper#7]
Hi @l4rm4nd,

I am from [Proxycurl](https://proxycurl.co/), we came across your repo and we would like to sponsor you.

Are you keen?

**Comment by l4rm4nd** [comment]
Hey @josephlimtech,

thanks for reaching out!

I've enabled the GitHub Sponsors button for this repository. 

Feel free to be the first using it! Really appreciate the offer.

**Comment by josephlimtech** [comment]
Hi @l4rm4nd! Would you mind sharing your email address so we can continue the conversation through email instead? Thank you!

**Comment by l4rm4nd** [comment]
> Hi @l4rm4nd! Would you mind sharing your email address so we can continue the conversation through email instead? Thank you!

Sure, it's `info@lrvt.de`.
